export const data=[
    {
        id:0,
        group:"hr-department",
        device:"samsung-hevin",
        os:"android",
    },
    {
        id:1,
        group:"deveolpment",
        device:"samsung-hevin",
        os:"ios",
    },
    {
        id:2,
        group:"hr-department",
        device:"samsung-hevin",
        os:"windows",
    },
    {
        id:3,
        group:"hr-department",
        device:"samsung-hevin",
        os:"android",
    },
    {
        id:4,
        group:"deveolpment",
        device:"samsung-hevin",
        os:"ios",
    },
    {
        id:5,
        group:"hr-department",
        device:"samsung-hevin",
        os:"windows",
    },
    {
        id:6,
        group:"hr-department",
        device:"samsung-hevin",
        os:"android",
    },
    {
        id:7,
        group:"deveolpment",
        device:"samsung-hevin",
        os:"ios",
    },
    {
        id:8,
        group:"hr-department",
        device:"samsung-hevin",
        os:"windows",
    },
    {
        id:9,
        group:"hr-department",
        device:"samsung-hevin",
        os:"android",
    }

]