export const devices=[
    {
        id:0,
        group:"HR Department",
        device:"apple-hevin",
        os:"android",
        name:"riyas"
    },
    {
        id:1,
        group:"Deveolpment",
        device:"vivo-1012",
        os:"apple",
        name:"riyas"
    },
    {
        id:2,
        group:"Support",
        device:"xiami-1212",
        os:"windows",
        name:"selva"
    },
    {
        id:3,
        group:"Sales",
        device:"Rmx-100",
        os:"android",
        name:"arun"
    },
    {
        id:4,
        group:"Deveolpment",
        device:"blockberry-111",
        os:"apple",
        name:"gowtham-114"
    },
    {
        id:5,
        group:"Margeting",
        device:"oppo-reno",
        os:"windows",
        name:"selva-115"
    },
    {
        id:6,
        group:"Support",
        device:"samsung-hevin",
        os:"android",
        name:"naveen-119"
    },
    {
        id:7,
        group:"Deveolpment",
        device:"samsung",
        os:"apple",
        name:"swaran-116"
    },
    {
        id:8,
        group:"HR Department",
        device:"hevin",
        os:"windows",
        name:"unknown-117"
    },
    {
        id:9,
        group:"Margeting",
        device:"samsung-hevin",
        os:"android",
        name:"user-118"
    }

]