export const devices = [
    {
        id: 0,
        title: "HR Department",
        title: "apple-hevin",
        type: "android",
        subtitle: "riyas",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 1,
        group: "Deveolpment",
        title: "vivo-1012-rmx-zion",
        type: "ios",
        subtitle: "riyas-sdfnskfndfnsdfsdnn",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 2,
        group: "Support",
        title: "xiami-1212",
        type: "windows",
        subtitle: "selva",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 3,
        group: "Sales",
        title: "Rmx-100",
        type: "android",
        subtitle: "arun",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 4,
        group: "Deveolpment",
        title: "blockberry-111",
        type: "ios",
        subtitle: "gowtham-114",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 5,
        group: "Margeting",
        title: "oppo-reno",
        type: "windows",
        subtitle: "selva-115",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 6,
        group: "Support",
        title: "samsung-hevin",
        type: "android",
        subtitle: "naveen-119",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 7,
        group: "Deveolpment",
        title: "samsung",
        type: "ios",
        subtitle: "swaran-116",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 8,
        group: "HR Department",
        title: "hevin",
        type: "windows",
        subtitle: "unknown-117",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 9,
        group: "Margeting",
        title: "samsung-hevin",
        type: "android",
        subtitle: "user-118",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 10,
        title: "HR Department",
        title: "apple-hevin",
        type: "android",
        subtitle: "riyas",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 11,
        group: "Deveolpment",
        title: "vivo-1012-rmx-zion",
        type: "ios",
        subtitle: "riyas-sdfnskfndfnsdfsdnn",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 12,
        group: "Support",
        title: "xiami-1212",
        type: "windows",
        subtitle: "selva",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 13,
        group: "Sales",
        title: "Rmx-100",
        type: "android",
        subtitle: "arun",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 14,
        group: "Deveolpment",
        title: "blockberry-111",
        type: "ios",
        subtitle: "gowtham-114",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 15,
        group: "Margeting",
        title: "oppo-reno",
        type: "windows",
        subtitle: "selva-115",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 16,
        group: "Support",
        title: "samsung-hevin",
        type: "android",
        subtitle: "naveen-119",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 17,
        group: "Deveolpment",
        title: "samsung",
        type: "ios",
        subtitle: "swaran-116",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 18,
        group: "HR Department",
        title: "hevin",
        type: "windows",
        subtitle: "unknown-117",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 19,
        group: "Margeting",
        title: "samsung-hevin",
        type: "android",
        subtitle: "user-118",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 20,
        title: "HR Department",
        title: "apple-hevin",
        type: "android",
        subtitle: "riyas",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 21,
        group: "Deveolpment",
        title: "vivo-1012-rmx-zion",
        type: "ios",
        subtitle: "riyas-sdfnskfndfnsdfsdnn",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 22,
        group: "Support",
        title: "xiami-1212",
        type: "windows",
        subtitle: "selva",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 23,
        group: "Sales",
        title: "Rmx-100",
        type: "android",
        subtitle: "arun",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 24,
        group: "Deveolpment",
        title: "blockberry-111",
        type: "ios",
        subtitle: "gowtham-114",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 25,
        group: "Margeting",
        title: "oppo-reno",
        type: "windows",
        subtitle: "selva-115",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 26,
        group: "Support",
        title: "samsung-hevin",
        type: "android",
        subtitle: "naveen-119",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 27,
        group: "Deveolpment",
        title: "samsung",
        type: "ios",
        subtitle: "swaran-116",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 28,
        group: "HR Department",
        title: "hevin",
        type: "windows",
        subtitle: "unknown-117",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 29,
        group: "Margeting",
        title: "samsung-hevin",
        type: "android",
        subtitle: "user-118",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 30,
        title: "HR Department",
        title: "apple-hevin",
        type: "android",
        subtitle: "riyas",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 31,
        group: "Deveolpment",
        title: "vivo-1012-rmx-zion",
        type: "ios",
        subtitle: "riyas-sdfnskfndfnsdfsdnn",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 32,
        group: "Support",
        title: "xiami-1212",
        type: "windows",
        subtitle: "selva",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 33,
        group: "Sales",
        title: "Rmx-100",
        type: "android",
        subtitle: "arun",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 34,
        group: "Deveolpment",
        title: "blockberry-111",
        type: "ios",
        subtitle: "gowtham-114",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 35,
        group: "Margeting",
        title: "oppo-reno",
        type: "windows",
        subtitle: "selva-115",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 36,
        group: "Support",
        title: "samsung-hevin",
        type: "android",
        subtitle: "naveen-119",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 37,
        group: "Deveolpment",
        title: "samsung",
        type: "ios",
        subtitle: "swaran-116",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 38,
        group: "HR Department",
        title: "hevin",
        type: "windows",
        subtitle: "unknown-117",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 39,
        group: "Margeting",
        title: "samsung-hevin",
        type: "android",
        subtitle: "user-118",
        icon: "fa-brands fa-android",
        data: null,
    },{
        id: 40,
        title: "HR Department",
        title: "apple-hevin",
        type: "android",
        subtitle: "riyas",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 41,
        group: "Deveolpment",
        title: "vivo-1012-rmx-zion",
        type: "ios",
        subtitle: "riyas-sdfnskfndfnsdfsdnn",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 42,
        group: "Support",
        title: "xiami-1212",
        type: "windows",
        subtitle: "selva",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 43,
        group: "Sales",
        title: "Rmx-100",
        type: "android",
        subtitle: "arun",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 44,
        group: "Deveolpment",
        title: "blockberry-111",
        type: "ios",
        subtitle: "gowtham-114",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 45,
        group: "Margeting",
        title: "oppo-reno",
        type: "windows",
        subtitle: "selva-115",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 46,
        group: "Support",
        title: "samsung-hevin",
        type: "android",
        subtitle: "naveen-119",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 47,
        group: "Deveolpment",
        title: "samsung",
        type: "ios",
        subtitle: "swaran-116",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 48,
        group: "HR Department",
        title: "hevin",
        type: "windows",
        subtitle: "unknown-117",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 49,
        group: "Margeting",
        title: "samsung-hevin",
        type: "android",
        subtitle: "user-118",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 50,
        title: "HR Department",
        title: "apple-hevin",
        type: "android",
        subtitle: "riyas",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 51,
        group: "Deveolpment",
        title: "vivo-1012-rmx-zion",
        type: "ios",
        subtitle: "riyas-sdfnskfndfnsdfsdnn",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 52,
        group: "Support",
        title: "xiami-1212",
        type: "windows",
        subtitle: "selva",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 53,
        group: "Sales",
        title: "Rmx-100",
        type: "android",
        subtitle: "arun",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 54,
        group: "Deveolpment",
        title: "blockberry-111",
        type: "ios",
        subtitle: "gowtham-114",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 55,
        group: "Margeting",
        title: "oppo-reno",
        type: "windows",
        subtitle: "selva-115",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 56,
        group: "Support",
        title: "samsung-hevin",
        type: "android",
        subtitle: "naveen-119",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 57,
        group: "Deveolpment",
        title: "samsung",
        type: "ios",
        subtitle: "swaran-116",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 58,
        group: "HR Department",
        title: "hevin",
        type: "windows",
        subtitle: "unknown-117",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 59,
        group: "Margeting",
        title: "samsung-hevin",
        type: "android",
        subtitle: "user-118",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 50,
        title: "HR Department",
        title: "apple-hevin",
        type: "android",
        subtitle: "riyas",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 61,
        group: "Deveolpment",
        title: "vivo-1012-rmx-zion",
        type: "ios",
        subtitle: "riyas-sdfnskfndfnsdfsdnn",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 62,
        group: "Support",
        title: "xiami-1212",
        type: "windows",
        subtitle: "selva",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 63,
        group: "Sales",
        title: "Rmx-100",
        type: "android",
        subtitle: "arun",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 64,
        group: "Deveolpment",
        title: "blockberry-111",
        type: "ios",
        subtitle: "gowtham-114",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 65,
        group: "Margeting",
        title: "oppo-reno",
        type: "windows",
        subtitle: "selva-115",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 66,
        group: "Support",
        title: "samsung-hevin",
        type: "android",
        subtitle: "naveen-119",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 67,
        group: "Deveolpment",
        title: "samsung",
        type: "ios",
        subtitle: "swaran-116",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 68,
        group: "HR Department",
        title: "hevin",
        type: "windows",
        subtitle: "unknown-117",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 69,
        group: "Margeting",
        title: "samsung-hevin",
        type: "android",
        subtitle: "user-118",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 70,
        title: "HR Department",
        title: "apple-hevin",
        type: "android",
        subtitle: "riyas",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 71,
        group: "Deveolpment",
        title: "vivo-1012-rmx-zion",
        type: "ios",
        subtitle: "riyas-sdfnskfndfnsdfsdnn",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 72,
        group: "Support",
        title: "xiami-1212",
        type: "windows",
        subtitle: "selva",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 73,
        group: "Sales",
        title: "Rmx-100",
        type: "android",
        subtitle: "arun",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 74,
        group: "Deveolpment",
        title: "blockberry-111",
        type: "ios",
        subtitle: "gowtham-114",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 75,
        group: "Margeting",
        title: "oppo-reno",
        type: "windows",
        subtitle: "selva-115",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 76,
        group: "Support",
        title: "samsung-hevin",
        type: "android",
        subtitle: "naveen-119",
        icon: "fa-brands fa-android",
        data: null,
    },
    {
        id: 77,
        group: "Deveolpment",
        title: "samsung",
        type: "ios",
        subtitle: "swaran-116",
        icon: "fa-brands fa-apple",
        data: null,
    },
    {
        id: 78,
        group: "HR Department",
        title: "hevin",
        type: "windows",
        subtitle: "unknown-117",
        icon: "fa-brands fa-windows",
        data: null,
    },
    {
        id: 79,
        group: "Margeting",
        title: "samsung-hevin",
        type: "android",
        subtitle: "user-118",
        icon: "fa-brands fa-android",
        data: null,
    }

]